name: Comicarr
version: 0.31.0-1
slug: comicarr
description: Automated comic book and manga management for Home Assistant
url: https://github.com/rigerc/ha-apps-next
arch:
  - aarch64
  - amd64
image: ghcr.io/rigerc/ha-addon-comicarr
init: false
startup: application
stage: experimental
backup: cold
map:
  - type: media
    read_only: false
  - type: share
    read_only: false
ports:
  8090/tcp: 8090
ports_description:
  8090/tcp: Comicarr web interface
webui: http://[HOST]:[PORT:8090]/
watchdog: http://[HOST]:[PORT:8090]/api/health
timeout: 300
apparmor: true
options:
  timezone: Etc/UTC
  log_level: normal
schema:
  timezone: str
  log_level: list(warning|normal|debug)
